### ISSUE TITLE
Is it compatible with fody plugins? 

### ISSUE THREAD

**Issue by friuns2** [ByronMayne/Weaver#16]
Is it compatible with fody plugins? 
can i for example add nullguard plugin?

**Comment by friuns2** [comment]
Do you think its possible to integrate fody? Unity networking have also own open source waever but its not compatible with fody as well..

**Comment by ByronMayne** [comment]
It would be quite the task to tell you the truth. Fody is using a different version of C# so you could not just plug and play. In newer Unity versions you could tell it to use the newer versions of DotNet but I don't want to put that as a requirement to using Weaver, since that is restricting. 

That being said I have not dug super deep into the source of Fody so their might be a simpler way to get things done.
