### ISSUE TITLE
Just checking something

### ISSUE THREAD

**Issue by Saishy** [ByronMayne/Weaver#2]
![Image of Weaver Settings](https://i.imgur.com/G9Ttqas.png)

Just wanted to know if the default settings upon cloning the repository is right, as it seems to have one blank assembly?

**Comment by ByronMayne** [comment]
If you took the setting Scriptable Object from the project it was just the one I was testing while building it. I had a few issues (that I resolved) that caused options to not be saved. Feel free to just put the arry size to one. 

Right now it checks to see if the file exists before trying to modify them and since it's blank it returns false so it skips it. There is no harm in it being there.

**Comment by ByronMayne** [comment]
As an improvement I should clear any blank ones or warn users if the assembly at that location does not exist.

**Comment by ByronMayne** [comment]
![missingassembly](https://user-images.githubusercontent.com/6024487/33412108-6dfb83f2-d557-11e7-905e-98a7e3c8be1c.PNG)

I added a missing assembly tag (it' needs a better layout but it works for now). This should help clear things up for people.
