### ISSUE TITLE
Behaviour is missing

### ISSUE THREAD

**Issue by IlyaBokovenko** [ByronMayne/Weaver#33]
Hello Byron. Do you still support Weaver? Here is the project attached in which I use Weaver to inject logging into TestScript. When first pushing "Play" everything looks fine. But the second time Unity reports "Behaviour missing" on every script in weaved assembly.
And after that every assembly rebuild produces error "Copying the file failed"

[TestCecil.zip](https://github.com/ByronMayne/Weaver/files/12524125/TestCecil.zip)

**Comment by ByronMayne** [comment]
Hey there,

Unfortunately no, I am not allowed to due to no-concept contracts I have with my employment. I have also pretty much stopped using Unity for the last 5 years. As the run times change it could quite easily break Weaver since it's modifying the compiled source. 

I can accept pull requests but when it comes to new development or bug fixing I am not allowed.

**Comment by IlyaBokovenko** [comment]
Got it, thank you for response
