### ISSUE TITLE
Working on mac?

### ISSUE THREAD

**Issue by HalfVoxel** [ByronMayne/Weaver#9]
Hi

Great job on this!
Have you tried it on mac? I'm asking because I'm seeing some strange behaviors.
Somehow it seems to prevent Unity from reloading assemblies at all. I can see that the package processes the scrips properly and it does write correct assemblies to disk, but once I enable this package Unity will no longer load new changes to the scripts after the initial one.
So if I make a change to a script, I see Unity compiling it and everything, but when I press play I still get the same result as after the first time the package was enabled. Restarting Unity does make it load the latest changes however.
I also cannot seem to get it to work for standalone builds (tested x64 mac standalone). The PostProcessScene callback runs as it is supposed to, but the standalone player does not have the modified assemblies.

**Comment by ByronMayne** [comment]
Hey HalfVoxel,

I personally don't own a mac and I can't use a mac from the office so I am unable to test it :(. The one thing off the top of my head is that I know Unity does not copy the Unity assemblies from the installation folder into the resources folder  This might be causing the issue.

Are you seeing any errors in the console or any logs in the Weaver Console (the one on the scriptable object)?

Also what version of Unity are you currently rocking?

If my assumption is right you might see something along the lines of 'Unable to resolve assembly'.

**Comment by HalfVoxel** [comment]
Hi, thanks for getting back to me :)

Okay.
> I know Unity does not copy the Unity assemblies from the installation folder into the resources folder
Not quite sure which installation and resources folder you mean here. The resources folder in a standalone build?

> Are you seeing any errors in the console or any logs in the Weaver Console (the one on the scriptable object)?
Nope, and not in the Unity editor log either. Rewriting the dll files seems to work perfectly.
Unity seems to reload it *sometimes*, but not always. I really hope this is not a race condition... that would be horrible to debug.

> Also what version of Unity are you currently rocking?
I'm currently at 2017.1.1f1 as that's what I had installed. So the beforeAssemblyReload callback does exist on this version.

> If my assumption is right you might see something along the lines of 'Unable to resolve assembly'.
Not anywhere where I can see. The strange thing is that Unity can load the assembly sometimes, it just doesn't pick up on the changes if I modify scripts after that (even though the rewrite does run).

**Comment by ByronMayne** [comment]
No worries! 

Damn, I was hoping the logs would guide the way.  Could you post a screen shot of the log? 

There is a few points in where Weaver normally fails.

### Assemblies can't be resolved
This one has a lot of logging (because I broke this a bunch during development). We know this is not the case because there are not logs or exceptions (Cecil tosses these like there is no tomorrow). 

### Weaving not happening
Maybe the changes are not being written to disk correctly or something is failing during weaving. If you open them with MonoDevelop or any other decompiler can you see the changes? If you don't see the changes that is the bug right there.

### Assemblies not being loaded 
I use `(beforeAssemblyReload)[https://docs.unity3d.com/ScriptReference/AssemblyReloadEvents.html] ` callback to change the assemblies before Unity tries to load them. If this callback is not working you would not see the effects of the weaving after you make changes. However if you hit play you would. 
Could you enter playmode and see if the changes take effect?

### Invalid IL is being generated 
This one is a bit harder to find because with Cecil you can write horribly broken IL. I don't have any checks for this because I don't know how to do that yet. Normally Unity tosses some errors about not being able to read the assembly. I don't think this is it because you say there is no errors. 


Thanks for the help!

**Comment by HalfVoxel** [comment]
I'll get you the log soon, but I'll answer some of the questions first.

*Weaving not happening*
I have verified that the correct assemblies are written to disk. If I open them in Monodevelop the changes are there.

*Assemblies not being loaded*
This callback seems to be working. Entering play mode is what I use to test the changes with, and it's not being picked up there either.

*Invalid IL is being generated*
This is with your extensions without any significant changes. Also note that it does manage to load the assemblies sometimes, but not always. And the only thing I change is something like Debug.Log("Test1") to Debug.Log("Test2") and check if Unity pick up the changes.

I also tried adding a call to AssetDatabase.Refresh after the assemblies were saved, but that does not appear to have helped at first glance.

**Comment by ByronMayne** [comment]
Well that is some helpful information but I can't think of what might be happening. The dlls are there, they are modified, but are never loaded after the first time.

The only thing left would be that Unity refuses to reload the new assembly for some reason. This makes sense that when you close Unity and reopen it you see the changes.

I will have to try to debug this on mac. 

Quick question, are you having Weaver modify one of the generated assemblies ie. Assembly-CSharp? 

As for an easy way to get a diff on an assembly I do not have one. I personally just look up the changes with ILSpy to validate that they happened. A diff tool would be so much better.

**Comment by HalfVoxel** [comment]
Yeah it's really strange. I will try to experiment a bit more on my end.
My current guesses are that it is either a race condition, that the dll is invalid for some reason (likely some metadata) or that somehow assemblies are being locked (like using Unity's LockReloadAssemblies) in some way.

**Comment by HalfVoxel** [comment]
> Quick question, are you having Weaver modify one of the generated assemblies ie. Assembly-CSharp?

Yes. That dll only.

**Comment by ByronMayne** [comment]
Yeah it would seem super odd if they were checking some sort of hash just for mac. I will take a look at the source that Unity released and see if there is any difference between mac and windows for any functions that I am using.

**Comment by metzsg** [comment]
Hey guys, just grabbed this and am testing in a mac environment.  It looks to be working well so far.  The provided MethodTimer and PropertyChanged components are functioning, in both editor and builds.

@HalfVoxel The issue with the assemblies not being reloaded by Unity could be caused if you are importing types into a module that are already defined in that module. Cecil does a safety check for this if you import a TypeReference, but not if you import a System.Type.  Any line like `Module.Import(typeof(SomeTypeDefinedInModule))` could be the culprit.  I've run into this before and this turned out to be the issue.  Cheers!
